### PR TITLE
Replace log4j with commons-logging.

### PR DESCRIPTION
**Pull request by tfenne**
Eliminates the dependency on log4j in preference for commons-logging.

It is unusual for _libraries_ to depend on logging frameworks like log4j.  The norm in the JVM world is to either _not_ log and just raise exceptions with appropriate messages, or use commons-logging which is a thin wrapper and can route to any specific logging implementation (including log4j).

Given all the recent security issues with log4j, this seems like a good time to make this move.

### CODE REVIEW

**Comment by Kmannth** [comment]
@tfenne  Thanks for this patch it very useful for this project.   Please add a "Signed-off-by" link to your patch. 

How much testing has been done with this patch?

**Comment by lbergelson** [comment]
This seems like a good idea.  I was probably the one who suggested log4j in the first place but it turns out to not have been a particularly well considered suggestion.

**Comment by tfenne** [comment]
@Kmannth Sorry for the slow response.  No, no real testing has been done - I've been struggling to setup an environment to do the necessary building.  I was hoping that submitting a PR would trigger a CI build and tests, but I think that's not setup to happen on PRs from forks.

**Comment by tfenne** [comment]
Ok - this is my first time setting up to sign commits with a gpg key, but I think I've done it successfully.  I just added a newline at the end of the README, then amended the prior commit to and force-pushed.  Looks like Github recognizes the commit as signed now.

**Review by Kmannth — APPROVED** [review]
This patch looks good to me. 

I was able to test this patch and can confirm that in a test merge with GATK I was able to see GKL output in the GATK sterr files and things behaved like expected.

**Pull request merged**
